# Generated by Django 5.1.15 on 2026-09-20 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('is_mock', models.BooleanField(default=True, help_text='True if processed via Mock/Demo OCR service')),
                ('disclaimer', models.TextField(default="This tool extracts information from the uploaded prescription. It does not provide medical advice or replace a doctor's prescription. Please verify the extracted medicines, dosage, and instructions with a qualified healthcare professional.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=100)),
                ('dosage_form', models.CharField(blank=True, default='', max_length=100)),
                ('confidence', models.FloatField(default=0.9, help_text='Extraction/OCR confidence score (0.00 to 1.00)')),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('NEEDS_VERIFICATION', 'Needs Verification'), ('UNMATCHED', 'Unmatched')], default='NEEDS_VERIFICATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_matches', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescriptions.prescription')),
            ],
        ),
    ]
