# Generated by Django 5.1.15 on 2026-09-19 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(db_index=True, max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('area', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.FloatField(default=17.4455, help_text='Latitude coordinate')),
                ('longitude', models.FloatField(default=78.3846, help_text='Longitude coordinate')),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='22:00:00')),
                ('description', models.TextField(blank=True, null=True)),
                ('shop_image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop_name'], name='shops_medic_shop_na_550d7c_idx'), models.Index(fields=['city'], name='shops_medic_city_dc6282_idx'), models.Index(fields=['pincode'], name='shops_medic_pincode_4691be_idx'), models.Index(fields=['is_active', 'is_verified'], name='shops_medic_is_acti_be7570_idx')],
            },
        ),
    ]
