# Generated by Django 5.1.15 on 2026-09-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(db_index=True)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_inventories', to='medicines.medicine')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='shops.medicalshop')),
            ],
            options={
                'ordering': ['medicine__medicine_name', 'expiry_date'],
                'indexes': [models.Index(fields=['quantity'], name='inventory_s_quantit_1aec8a_idx'), models.Index(fields=['expiry_date'], name='inventory_s_expiry__c836bd_idx'), models.Index(fields=['is_available'], name='inventory_s_is_avai_4e027a_idx')],
                'unique_together': {('shop', 'medicine', 'batch_number')},
            },
        ),
    ]
