# Generated by Django 5.1.15 on 2026-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand_name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Ointment', 'Ointment'), ('Drops', 'Drops'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Other', 'Other')], default='Tablet', max_length=50)),
                ('manufacturer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('prescription_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['medicine_name'],
                'indexes': [models.Index(fields=['medicine_name'], name='medicines_m_medicin_d13421_idx'), models.Index(fields=['generic_name'], name='medicines_m_generic_1e9386_idx'), models.Index(fields=['brand_name'], name='medicines_m_brand_n_d788ba_idx'), models.Index(fields=['category'], name='medicines_m_categor_ea4e49_idx')],
                'unique_together': {('medicine_name', 'dosage', 'dosage_form')},
            },
        ),
    ]
